### ISSUE TITLE
Mass update content type in Drupal

### ISSUE THREAD

**Issue by EmilyBaron** [givingforum/givingforum#193] opened 2015-07-28 14:57 UTC
I recently realized that we weren't mapping Event Title to Salesforce and have since set up our mapping. For events we add from here on out, it will sync, but unless we update a past event, that info won't get to salesforce.  It obviously isn't very efficient for me to go in and open every event in drupal and save so it updates the field.  I asked Val about a mass update feature in drupal and this is what we can do (Val let me know if I missed something):

Themers can add a view that will be added to the backend with bulk operations capabilities. One of them will be customized to mass update whatever content type you want (like event).

Here’s how it’ll roughly look - http://www.awesomescreenshot.com/image/441422/c1822edfea9231e4f4d7f7dc7ea57f2a. 
The drop-down has tons of options.

We are definitely interested - is anyone else interested in this feature?

**Comment by vrozansky** [comment] 2015-07-28 15:03
Thanks for filing this ticket @EmilyBaron 

We can actually customize what bulk operation options we'd want in the drop-down. At the very least, we should have an option to mass update events that will trigger a sync to Salesforce, as you described.

My guess is that it'll require 3-5 hours of work (to be confirmed), so if all RAs will vote in favor of it, individual cost will be insignificant (around $25 or so).

Let's assign a deadline of August 11th, 2015 to this ticket. Please vote. Thank you.

**Comment by sgeis** [comment] 2015-07-28 17:43
Indiana is not interested at this time.

**Comment by MainePhilanthropyCenter** [comment] 2015-07-28 18:51
MPC is not interested at this time.

**Comment by mtrimbach** [comment] 2015-07-30 22:08
CNJG is not interested at this time.

**Comment by capitalgrits** [comment] 2015-08-03 17:14
WRAG is not interested at this time

**Comment by PhilOhio** [comment] 2015-08-04 15:08
POH is not interested

**Comment by wcorkill** [comment] 2015-08-05 14:51
CMF is not interested at this time.

**Comment by vrozansky** [comment] 2015-08-05 17:29
Here's a better screenshot of this new view that enables us to update any given event, a group of events, or all events. Same thing can be done with any content type though it's probably most useful for events because the view doesn't change anything in the actual event, but simply re-saves it and triggers a sync with Salesforce. This way we can easily update/sync all events in two clicks.

Please continue to vote. Deadline is August 11st, 2015. Thank you.

**Comment by vrozansky** [comment] 2015-08-05 17:30
Would be helpful if I actually included the screenshot :) Here it is - http://www.awesomescreenshot.com/image/462855/58ee930d761c87b1f9836d1dca3d88c5

**Comment by kristenruff** [comment] 2015-08-10 18:43
PNY is not interested.

**Comment by vrozansky** [comment] 2015-08-17 19:00
Resolving this ticket. GWP received this view and if others are interested in it later, please search resolved tickets and feel free to re-open it. We'll then add this view to your site and credit GWP accordingly. Thank you.

**Closed by vrozansky** 2015-08-17 19:00 UTC
Labels: Group Feedback Needed, Vote Required
