### ISSUE TITLE
Create a reminder for users who leave items in cart

### ISSUE THREAD

**Issue by DNTownsend** [givingforum/givingforum#175] opened 2015-01-06 17:02 UTC
We'd like to explore developing a reminder for users who leave items in their shopping cart without completing the checkout process. An auto-generated follow up email would be ideal for those to *think* they have registered for a program but have not completed all steps required. For those who purposefully abandon a registration, it would serve as a reminder to clean out their cart.

**Comment by vrozansky** [comment] 2015-01-06 17:17
Forum is interested. This is something that we might be able to with themers instead of TS and then import as a rule to each site. I see this as a scheduled rule that runs once a day (or once every 2 days), picks up items in cart, and then sends an email to users in question via Mandrill.

I'd project that it won't cost more than $1,000 to develop, test, and roll out. If all Drupal-using RAs are interested, it'll be about $60 each. I can also get an estimate from TS, but I'm guessing it'll be more expensive as we'll need to roll it into the distro as well.

Please vote. Thank you.

**Comment by allenlaurie** [comment] 2015-01-06 17:31
CCP is interested.

**Comment by wcorkill** [comment] 2015-01-06 18:45
I’m intersted.  There is a Drupal Commerce Notification module that might do what we are looking for. https://www.drupal.org/project/commerce_notification

**Comment by jonstahl** [comment] 2015-01-07 16:26
PNW is neutral. A constructive suggestion: it might be more useful as a first step to be able for admins to easily view abandoned orders, to track the extent to which the problem is happening, rather than simply building a system for automatic followup. This could be as simple as a view, I'm not sure if getting at commerce stuff is more complex than that.

**Comment by vrozansky** [comment] 2015-01-07 17:42
It's a good idea. I think we can possibly combine the two ideas by creating a bulk view for admins that will list all orders still in cart and allow site admins to trigger an email notification to users of choice. This won't be as automated as auto-emailing anyone who left an item in cart for X number of days, but more tailored.

I don't think this would significantly change the estimate for themers, but I can find out for sure if there's sufficient interest. Thank you.

**Comment by wcorkill** [comment] 2015-01-07 21:21
I’ll take a look at the views, but I think creating the view that Jon proposed would be easy enough.  If anyone has certain field requirements that they want included, just let me know.  I was thinking, cart owner, date of cart/order creation, amount and link to view items in the cart.  Any other details about the org or individual contact that you want should be easy to include.

**Comment by PhilOhio** [comment] 2015-02-04 16:26
POH is interested

**Comment by vrozansky** [comment] 2015-02-11 17:51
@wcorkill - please let us know if you had a chance to work on these views. If not, it's totally OK. I'm trying to line up this ticket for either themers or TS. Unfortunately, TS is charging now for estimates, so I'm being more selective than before.

Others, please weigh in on this ticket so we can determine the level of interest. Thank you.

**Comment by wcorkill** [comment] 2015-02-11 21:26
Val,  I did create a new custom view for this.  I have attached a pic of it below and we can export the view and put it on the Test-integration site so everyone can explore and test it out.  The view once imported will be under Store>Orders>Shopping Carts

The view looks for open cart orders and allows you to view the details about each open cart.  You can also use the filter to find carts that are in the Check Out state.  Some users get partially through checkout and never complete so this view will also help an admin find those as well.  I have experimented with Rules to try and send email notifications but I can't see an easy way to only send the user an email 1 time, instead it wants to send the user an email every time Cron runs (which I don't think they would appreciate).  I'll try a couple more things on that but we might want to engage themers or TS on the notification piece.
![shopping cart view](https://cloud.githubusercontent.com/assets/4803610/6156677/0e3f46ba-b20a-11e4-9763-ba06ee9f5342.png)

**Comment by wcorkill** [comment] 2015-02-11 21:31
The above view is available here:http://live-integration.gotpantheon.com/admin/commerce/orders/carts
 
If anyone forogt the Control Site login is: admin / KM2013

**Comment by vrozansky** [comment] 2015-02-11 22:00
Thanks @wcorkill. Seems like I'm chatting with you about this on GitHub and Skype at the same time :)
I'd encourage everyone to take a look at the view and provide your comments here. It's pretty simple to adjust it, so all comments are welcome. We'll then work with ThinkShout on figuring out the reminder emails so they're sent only once or twice.

**Comment by jonstahl** [comment] 2015-02-11 22:03
This looks nice. I'd like to see what event/product the order is for.

**Comment by wcorkill** [comment] 2015-02-11 23:28
I'll have to see if I can list the items below each order, it might be tricky, but you can always click on the order to see the details.

Sent from my iPhone

On Feb 11, 2015, at 5:03 PM, Jon Stahl <notifications@github.com<mailto:notifications@github.com>> wrote:


This looks nice. I'd like to see what event/product the order is for.

-

**Comment by EmilyBaron** [comment] 2015-02-17 11:25
GWP is not interested at this time.

**Comment by PhilOhio** [comment] 2015-04-23 16:30
Hi @wcorkill  @vrozansky, Has a decision been made regarding this? If I missed it my apologies. We are having issues with incomplete shopping carts and people showing up to programs who thought they registered.  Also we are a little confused with the terminology. Are registrations considered incomplete unless it says "checkout: checkout." Right now it is very hard to determine where the person is in the process. Also. the view is sorting by the updated field and it is somehow pulling old registrations. Even ones from last year and putting today's date. See screenshot: http://awesomescreenshot.com/0a44uok01d You can see the old order number and it is even showing me as admin because I clicked a program this morning but I never hit register or anything. Is it possible to update this view some so we can figure out what is actually incomplete.

**Comment by vrozansky** [comment] 2015-04-23 17:01
This ticket is still in ThinkShout's queue with a tag of 2.7.4 so it'll be included in the upcoming release. The view that Bill developed above on our control site - http://live-integration.gotpantheon.com/admin/commerce/orders/carts - can easily be imported to your site and should give you a little more clarity.

I never really look at the orders view to check registrations and instead go to a specific event and Manage Registrations there. If the Registration State is complete, then I know it synced to Salesforce, confirmation email sent to the registrant (per rule configuration), and transaction is completed. If it's Pending, then you can click through and investigate further about the state of any given registration.

We can update the view, of course. Any recommendations (from everyone) are welcome. Thanks.

**Comment by PhilOhio** [comment] 2015-04-23 17:22
Only thing about manage registrations is it doesn’t show people who have a program sitting in their cart though. We need a way to view pending on a page so we don’t have to click each person individually. I registered and put a program in my cart. I didn’t submit though but it doesn’t show up anywhere.
Also we had someone’s credit card declined but we didn’t know that and it never registered her and it doesn’t show as pending but shows her as complete online but not registered in SF and doesn’t show her in managed registrations.
I think we need a little help with this.


. . . . . . . . . . . . . . . . . . . . . . . . .
Stacey Wilson | Member Services Associate, Digital Content | Philanthropy Ohio
37 W. Broad St., Suite 800 | Columbus, OH 43215 | phone 614.224.1344 | direct 614.914.2247
www.philanthropyohio.org<http://www.philanthropyohio.org/>

[FINAL-teal-social-facebook-circle-100x100]<http://www.facebook.com/philanthropyohio>[3teal-social-Twitter-circle-100x100]<http://www.twitter.com/philanthropyoh>[FINAL-teal-social-LinkedIn100x100]<http://www.linkedin.com/company/philanthropyohio>[FINAL-teal-social-blog-circle-100x100]<http://letstalkphilanthropy.wordpress.com/>

**Comment by vrozansky** [comment] 2015-04-23 18:55
Let me add the view from the control site to your site so you can easily see which registrations are sitting in the shopping cart and haven't been checked out. Users should also be able to see it as there's a number next to the cart link until checkout is completed. It's on your site already, actually (and I kept the default Shopping Carts tab as well).

Manage Registrations tab doesn't show whether user added something to the cart because technically it's not a registration yet (they may have added it to cart to see the actual price, for example). That's why I agree that it's helpful to look at the Shopping Carts tab to see what's still there (though not exactly actionable) and then a new rule that triggers notifications to users will also be helpful.

The credit card issue used to happen before, but was fixed in version 2.6.6, which you (and all of us) have on live sites. This must be an old case or something else is going on. Bill in Michigan originally reported it and Tauno fixed it for 2.6.6 release. It hasn't recurred since.

**Comment by PhilOhio** [comment] 2015-04-23 19:15
Thanks Val. I decided to email you off of github so we can discuss this without everyone getting multiple emails ☺
I can see the view and just have a question regarding the criteria. It defaults to -3 days.
The credit card was declined April 16. Here is the order https://www.philanthropyohio.org/admin/commerce/orders/1020/payment

. . . . . . . . . . . . . . . . . . . . . . . . .
Stacey Wilson | Member Services Associate, Digital Content | Philanthropy Ohio
37 W. Broad St., Suite 800 | Columbus, OH 43215 | phone 614.224.1344 | direct 614.914.2247
www.philanthropyohio.org<http://www.philanthropyohio.org/>

[FINAL-teal-social-facebook-circle-100x100]<http://www.facebook.com/philanthropyohio>[3teal-social-Twitter-circle-100x100]<http://www.twitter.com/philanthropyoh>[FINAL-teal-social-LinkedIn100x100]<http://www.linkedin.com/company/philanthropyohio>[FINAL-teal-social-blog-circle-100x100]<http://letstalkphilanthropy.wordpress.com/>

**Comment by wcorkill** [comment] 2015-04-29 15:34
Stacey,  I'm not sure if your question is about the time window or what the view is showing, but I built the view with the 3 day default and to show incomplete orders.  It was really just an arbitrary date we decided on based on our business needs.  You typically don't need to address things that have been in a cart for weeks and as long as you are checking this view a couple times a week, so 3 days should allow you to capture those abandoned carts in a pretty recent time window so you can get reminders out to users if needed.  The good news is that you could push this out to 1,3, 7, 14, etc. days if you want.  

Also registrations won't get created until the order is completed so a user should not get a registration if the card is declined the order would likely be stuck in the payment stage of checkout.  We actually see a lot of people stop on the last checkout screen not realizing they have to hit the final checkout button to finish the order, so that is where we see many orders left at, which also doesn't get them a confirmation or registration.

**Comment by wcorkill** [comment] 2015-04-29 15:53
Maybe I should clarify this a little better about the 3 days in the view.  the 3 days is how much time we allow users to come back and complete their order on their own before they appear on the view. After 3 days, we thought they might have forgotten about the order.

**Comment by vrozansky** [comment] 2015-06-02 21:41
So ThinkShout updated this ticket finally. It's not looking very promising. Please see their comment and estimate below and weigh in. The quicker everyone responds the quicker we'll be able to move forward, explore another way (see above), or resolve this ticket. Thank you.

*********
"I think the commerce_notification module is not a bad starting point to think about this problem, but it's not the complete solution.
The commerce_notification module offers Commerce VBO integration, an admin view of all abandoned orders, which Val has flagged as a requirement ("admins should be able to easily view abandoned orders and track them"), and appears to take care of only sending a notification once per order. What it does not do is allow for the automated scheduling of reminder emails.
This feature does appear under the "roadmap" section on the module page.

Estimate for this task: 16 hours"

**Comment by jonstahl** [comment] 2015-06-02 22:02
My feeling is that the cost of this appears to exceed its value. I think the view of abandoned orders may be a good low-hanging starting point, and we can explore automated notifications from there.

**Comment by AClay2** [comment] 2015-06-02 22:04
I would agree with Jon on this.

[PhilanthropySouthwest]

adrienne Clay
Office Manager & Database Administrator
Phone 214-740-1787
Fax 214-740-1790
[facebook]<https://www.facebook.com/PhilanthropySouthwest>[linkedin]<https://www.linkedin.com/company/458770>[twitter]<https://twitter.com/@southwestfdns>

**Comment by mtrimbach** [comment] 2015-06-02 22:59
CNJG not interested at that cost.

**Comment by EmilyBaron** [comment] 2015-06-04 10:03
I would agree with Jon on this also..not worth the cost at this time.

**Comment by vrozansky** [comment] 2015-07-27 20:03
I'll give this ticket a little more time, until August 10th. If others agree that the estimate exceeds the value, then we'll close the ticket. Please weigh in. Thank you.

**Comment by sgeis** [comment] 2015-07-28 17:57
Indiana thinks the cost outweighs the benefit. We might be interested in the future if there is a less expensive option.

**Comment by MainePhilanthropyCenter** [comment] 2015-07-28 19:20
MPC is fairly certain the view is sufficient for our needs.

**Comment by PhilOhio** [comment] 2015-08-04 15:03
POH also agrees with Jon on this.

**Comment by kristenruff** [comment] 2015-08-10 18:44
PNY not interested.

**Comment by vrozansky** [comment] 2015-08-20 16:24
Seems like we have a consensus that ThinkShout's estimate for this task is just too high.I'll tag this ticket with "Parking Lot" and resolve. Feel free to copy the view that Bill developed here - http://live-integration.gotpantheon.com/admin/commerce/orders/carts - in the meantime or contact me offline for assistance. Anyone is welcome to re-open this ticket for additional feedback or suggestions. Thank you.

**Closed by vrozansky** 2015-08-20 16:24 UTC
Labels: Group Feedback Needed, Parking Lot
